apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: applications.extras.automium.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.name
    description: Application name
    name: Application
    type: string
  - JSONPath: .spec.cluster
    description: Target cluster
    name: Cluster
    type: string
  - JSONPath: .spec.version
    description: Monitoring stack version
    name: Version
    type: string
  - JSONPath: .status.phase
    description: The execution phase
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: extras.automium.io
  names:
    kind: Application
    plural: applications
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              description: Cluster is the cluster name in Rancher.
              type: string
            name:
              description: Name is the name of the extra application to deploy.
              type: string
            namespace:
              description: Namespace is the Kubernetes target namespace. If it exists,
                it will be moved into the Project defined in this resource.
              type: string
            parameters:
              description: Parameters are the custom answers that will be provided
                when deploying the extra application.
              type: object
            project:
              description: Project is the Rancher project where the extra applicaton
                will be deployed.
              type: string
            version:
              description: Version is the version of the extra application to deploy.
              type: string
          required:
          - name
          - version
          - cluster
          - project
          - namespace
          type: object
        status:
          properties:
            error:
              description: Error is the error string populated if something wrong
                happend during the deploy.
              type: string
            phase:
              description: Phase is the deploy status as reported from Rancher.
              type: string
          required:
          - phase
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
