apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: monitorings.extras.automium.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.cluster
    description: Target cluster
    name: Cluster
    type: string
  - JSONPath: .spec.version
    description: Monitoring stack version
    name: Version
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: extras.automium.io
  names:
    kind: Monitoring
    plural: monitorings
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              description: Cluster is the Rancher name for the target cluster.
              type: string
            parameters:
              description: Parameters are custom answers for the Monitoring application.
              type: object
            version:
              description: Version is the version of the Monitoring application to
                deploy.
              type: string
          required:
          - cluster
          - version
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
