apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  sync:
    syncOnly:
    - group: core.automium.io
      kind: Service
      version: v1beta1
    - kind: Namespace
      version: v1