kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-role
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "statefulsets", "statefulsets/scale"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]