apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8suniqueservice
metadata:
  name: force-automium-unique-service-name
spec:
  match:
    kinds:
    - apiGroups:
      - core.automium.io
      kinds:
      - Service