apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sdeleteactiveservice
metadata:
  name: prevent-automium-service-deletion
spec:
  match:
    kinds:
    - apiGroups:
      - core.automium.io
      kinds:
      - Service