openapi: "3.0.0"
info:
  version: 1.0.0
  title: Automium CRDs
  license:
    name: MIT
paths:
  /:
    get:
      summary: List all Nodes
      responses:
        '200':
          description: An array of Nodes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nodes"
    post:
      summary: Create a Node
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Node"
components:
  schemas:
    Nodes:
        type: array
        items:
            $ref: "#/components/schemas/Node"
    Node:
        required:
        - metadata
        - apiVersion
        - kind
        - spec
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              deletionDate:
                type: string
              hostname:
                type: string
            required:
            - hostname
            - deletionDate
            type: object
          status:
            properties:
              nodeHealthChecks:
                items:
                  properties:
                    checkID:
                      type: string
                    name:
                      type: string
                    output:
                      type: string
                    serviceID:
                      type: string
                    serviceName:
                      type: string
                    status:
                      type: string
                  required:
                  - checkID
                  - name
                  - status
                  - output
                  - serviceID
                  - serviceName
                  type: object
                type: array
              nodeProperties:
                properties:
                  address:
                    type: string
                  flavor:
                    type: string
                  id:
                    type: string
                  image:
                    type: string
                  node:
                    type: string
                  publicAddress:
                    type: string
                required:
                - id
                - node
                - address
                - publicAddress
                - flavor
                - image
                type: object